/* This file includes the autogenerated configuration headers
 * please do not edit the included files, edit the .conf
 * files instead and run make to rebuild the headers
 */


#ifndef _STATES_CONF_
#define _STATES_CONF_

/* state/action, animation and condition lists */
#include "states_conf_static.h"
/* condition properties */
#include "states_conf_properties.h"

#endif

