#!/bin/bash
#Syncmail: Send a mail when a file is commited in the Lugfi GF
# Note: sed, whoami and date will be required


old=`echo $1|sed -e "s/^\(.*\),.*,.*\$/\1/g"`
new=`echo $1|sed -e "s/^.*,\(.*\),.*\$/\1/g"`
file=`echo $1|sed -e "s/^.*,.*,\(.*\)\$/\1/g"`

echo -e "hola $file $new $old" >>~/cvsout

#cat mailtest - |sed -e "s/(user)/`whoami`/g"|/home/users/ecalot/telnet localhost 25

