/* Code below was generated by a machine, so please don't edit */

class board {
	public:
	unsigned long long board[2];
	int actualPlayer;

	inline void clear() {
		board[0] = 0;
		board[1] = 0;
		actualPlayer = 0;
	}
	inline int putToken44(int column);
	inline int removeToken44(int column);
};

inline board::putToken44(int column) {
	switch(column) {
		case 0:
			break;
		case 1:
			break;
		case 2:
			break;
		case 3:
			break;
	};
}

